export const selfAssessmentGuides = {
  Beekeeping: {
    title: "Self-Assessment Guide - Beekeeping",
    sections: [
      {
        heading: "ESTABLISH HIVED COLONIES IN A BEE YARD",
        title: "ESTABLISH HIVED COLONIES IN A BEE YARD",
        questions: [
          "Identify species of bee that can be grown and has economic feasibility *",
          "Identify the characteristics of a reliable source/supplier of hives and hive stand",
          "Select hive appropriate to the species of bee and checks its cleanliness*",
          "Inspect specification requirements of hives and hive stand *",
          "Select location favorable for setting-up hive *",
          "Discuss the installation of starter colony of specific species",
          "Demonstrate cleaning and disinfection of hives",
          "Check working condition of hives and performs simple repair, if necessary",
          "Check the need to replenish food following industry practice",
          "Clean, make inventory and store tools & equipment after establishing hived colonies",
          "Manage wastes (reduce, reuse, recycle) and/or disposes following environmental regulations",
          "Apply safety and health measures according to safety and health standards of industry *",
        ],
      },
      {
        heading: "MANAGE BEE COLONY",
        title: "MANAGE BEE COLONY",
        questions: [
          "Inspect bee colony for pests and/or diseases following industry practice *",
          "Clean hives and rotate frame to prevent diseases, following industry practice",
          "Demonstrate treatment and/or apply corrective measures on bee colony with pests/diseases following industry practice *",
          "Identify type of feed supplement and computes amount needed for a given number of colonies *",
          "Demonstrate preparation of different types of feed following industry practice *",
          "Demonstrate feeding using different types of feeder following industry practice *",
          "Identify factors to consider when assessing health and performance of colony",
          "Assess health and performance of colony following industry practice *",
          "Identify health status of queen bees through its egg laying pattern *",
          "Identify and apply corrective measures (ex. provision of sufficient food supply) to improve health and performance of bee, if any *",
          "Identify indicators of the need to requeen colonies following industry practice *",
          "Demonstrate re-queening procedure (particularly queen catching and marking) following industry practice *",
          "Identify indicators of the need to merge colonies *",
          "Demonstrate merging colonies using appropriate tools/materials and following industry practice",
          "Identify indicators and reasons for bee swarming *",
          "Assess condition on bee swarming and perform preventive measure, if necessary",
          "Describe how to capture bee swarm using appropriate tools and equipment and following industry procedure *",
          "Apply safety and health measures according to safety and health standards of industry *",
        ],
      },
      {
        heading: "PROPAGATE BEE COLONY",
        title: "PROPAGATE BEE COLONY",
        questions: [
          "Describe preparatory activities for propagating bee colony following industry practice (ex. needed tools, use of PPE)",
          "Identify indicators on readiness of colony to divide *",
          "Assess status and strength of colony (ex. presence of good queen, sufficiency of food supply, presence of pest/diseases)",
          "Describe preparation of queenless nucs colony following industry practice",
          "Demonstrate division of colony according to industry practice *",
          "Demonstrate introduction of queen to nucs, following industry practice *",
          "Identify indicators on status of queen acceptance",
          "Check food sufficiency and demonstrates feeding of nucleus/starter colony",
          "Enumerate ways to maintain a newly established colony (ex. treat/applies corrective measures, checking food sufficiency and monitoring health and performance) *",
          "Apply safety and health measures according to safety and health standards of industry *",
        ],
      },
      {
        heading: "CONDUCT HARVESTING OPERATION",
        title: "CONDUCT HARVESTING OPERATION",
        questions: [
          "Conduct preparatory activities of harvesting operations following industry practice (ex. needed tools, use of PPE, checking the weather) *",
          "Identify type of bee products to be harvested *",
          "Demonstrate different harvesting procedures according to type of bee products, using appropriate tools/materials following industry practice *",
          "Place harvested bee products in containers, observing food safety on handling products *",
          "Place stickies and drawn combs inside the hive in preparation for the next harvest",
          "Clean and store harvesting tools and equipment *",
          "Record amount of harvested products following industry procedure*",
          "Apply safety and health measures according to safety and health standards of industry *",
        ],
      },
      {
        heading: "PROVIDE POLLINATION SERVICES",
        title: "PROVIDE POLLINATION SERVICES",
        questions: [
          "Identify species of bees compatible to the crop to be pollinated according to industry practices *",
          "Determine the number, location and types of colonies based on crop requirements for effective pollination *",
          "Identify environmental/local government rules/policies that will affect the provision of pollination services",
          "Assess strength, condition and health of bee colonies that will be used for pollination services, according to industry practice *",
          "Identify potential risk to pollination activities posed by environmental condition",
          "Determine preventive measures for potential risks identified",
          "Provide client with technical information (includes bee performance, health and safety of colony, protection against pesticide/pests) on bees following workplace procedure *",
          "Discuss with client the details of services (including schedule, scope and coverage) that will be provided to reach an agreement *",
          "Demonstrate packaging technique of colony to be transported, following industry standard *",
          "Identify required environmental/local government permits to be secured before transporting bee colonies",
          "Describe how to sets-up colonies according to industry procedure *",
          "Describe ways to care for bees and ensure apiary/meliponary perfomance following industry procedure (ex. food sufficiency)",
          "Record information needed before provision of pollination services",
          "Describe a successfully completed transaction/agreement on pollination services",
        ],
      },
    ],
  },
  "Caregiving NCII": {
    title: "Self-Assessment Guide - Caregiving NC II",
    sections: [
      { project: "Project 1", heading: "PROVIDE CARE AND SUPPORT TO INFANTS/TODDLERS AND CHILDREN", title: "PROVIDE CARE AND SUPPORT TO INFANTS/TODDLERS AND CHILDREN", questions: [] },
      { project: "Project 1", heading: "Provide care and support to infants/toddlers and children", questions: ["Understand the characteristics of infants/toddlers", "Identify signs of hunger, distress and pain demonstrated by infants", "Establish bonding with infants and toddlers", "Perform proper hand washing techniques and procedures", "Perform procedures in bathing and dressing infants and toddlers", "Change infant diapers appropriately", "Prepare milk formula as prescribed", "Perform procedures in feeding and burping", "Provide activities to put infants and toddlers to rest and sleep", "Respond to physical, emotional, social, intellectual and creative needs of infants and toddlers"] },
      { project: "Project 1", heading: "Provide care and support to children", questions: ["Teach hygiene practices to children", "Deal with bathroom/comfort room accidents in a manner that provide protection to the child’s esteem and privacy", "Dress up children according to weather condition and /or child’s culture/preferences", "Follow safe handling and maintenance of child’s school paraphernalia, toys and other personal things", "Perform the procedures in taking vital signs"] },
      { project: "Project 1", heading: "Foster physical development of children", questions: ["Explain the physical growth and development of infant/toddler", "Determine types of activities that will foster physical development", "Organize indoor and outdoor recreational activities that enhance growth and motor skills development", "Understand the importance of rest and sleep for child’s growth", "Understand the social, intellectual, creative and emotional development of children"] },
      { project: "Project 1", heading: "Foster social, intellectual, creative and emotional development of children", questions: ["Provide activities that will develop self-help skills and independence", "Provide opportunities for children to express their feelings, ideas and needs", "Enhance children’s awareness and creativity", "Foster positive discipline", "Respect individual differences of children"] },
      { project: "Project 1", heading: "Respond to emergencies", questions: ["Perform CPR to infant/toddler", "Handle properly infant milk choking", "Respond to convulsion due to high fever"] },
      { project: "Project 1", heading: "Prepare hot and cold meals", questions: ["Prepare foods suited to child’s age, health and cultural requirements", "Ensure freshness/quality of food serving"] },
      { project: "Project 1", heading: "Maintain healthy and safe environment", questions: ["Determine environmental, health and safety standards", "Identify potential hazards indoor and outdoor", "Follow safety procedures and regulations"] },
      { project: "Project 1", heading: "Establish Professionalism at The Workplace", questions: ["Observe and maintain personal hygiene and good grooming at all times", "Maintain cleanliness and orderliness of workplace", "Consider culture, customs and traditions of client"] },
      { project: "Project 2", heading: "PROVIDE CARE AND SUPPORT TO ELDERLY AND PEOPLE WITH SPECIAL NEEDS", title: "PROVIDE CARE AND SUPPORT TO ELDERLY AND PEOPLE WITH SPECIAL NEEDS", questions: [] },
      { project: "Project 2", heading: "Provide care and services to elderly", questions: ["Understand the characteristics of general aging process*", "Identify the physical and psychological needs of elderly*", "Use effective communication skills*", "Assist elderly in their personal needs*", "Assist elderly in performing daily activities*", "Maintain respect on right and preferences of the elderly client*", "Provide safety precautions in the environment*"] },
      { project: "Project 2", heading: "Provide care and services to people with special needs", questions: ["Establish appropriate relationship to people with special needs*", "Understand the requirements of people with special needs*", "Assist people with special needs in meeting their requirements*", "Assist in maintaining an environment that enables people with special need to have maximum independent living*"] },
      { project: "Project 2", heading: "Maintain healthy and safe environment", questions: ["Determine environmental, health and safe hazards*", "Maintain proper lighting, heating and cooling ventilation*", "Observe organizational policies and procedures for safety and environmental protection*", "Recognize symbols of hazardous materials ex. Flammable*"] },
      { project: "Project 2", heading: "Respond to emergencies", questions: ["Observe universal rules of precaution for infection control*", "Use appropriate protection device for infection control*", "Recognize emergency sign and symptoms of illness (heart disease CVA, diabetes, etc)*", "Seek for medical assistance as necessary according to policies and procedure*", "Provide comfort and assurance*", "Identify first aid procedures*", "Perform adult CPR*"] },
      { project: "Project 2", heading: "Prepare hot and cold meals", questions: ["Plan meals according to health and cultural preferences*", "Prepare and cooks ingredients according to recipe*", "Identify the uses and specifications of cooking tools and equipment*", "Perform basic table setting and servicing*", "Ensure freshness/quality of food served*", "Observe safety and maintenance of cooking tools and equipment*", "Observe personal hygiene and sanitation while cooking *"] },
      { project: "Project 2", heading: "Establish professionalism in the workplace", questions: ["Exhibit willingness, enthusiasm and commitment to do the job*", "Assume full responsibility of work*", "Consider culture, customs and traditions of client*", "Observe positive work values and ethics*", "Maintain personal hygiene and good grooming at all times*", "Maintain professional relationship with client*"] },
      { project: "Project 3", heading: "PERFORM HOUSEKEEPING ACTIVITIES", title: "PERFORM HOUSEKEEPING ACTIVITIES", questions: [] },
      { project: "Project 3", heading: "Maintain healthy and safe environment", questions: ["Use the appropriate cleaning tools and equipment*", "Determine environmental, health and safe hazard*", "Recognize symbols of hazardous materials (flammable, toxic)*", "Follow safety procedures and regulations*"] },
      { project: "Project 3", heading: "Clean living, dining and bedroom, toilet and bathroom", questions: ["Apply suitable cleaning techniques and maintenance to different floor type and surface texture, ceilings and walls*", "Operate and maintains cleaning tools and equipment*", "Utilize appropriate cleaning materials and supplies*", "Dispose garbage and contaminated waste properly*", "Utilize proper sanitation techniques for infection control*", "Observe safety rules in cleaning*", "Arrange furnishings and fixtures for comfort, convenience and safety*", "Observe safety rules to prevent injury and damage to property*"] },
      { project: "Project 3", heading: "Wash and iron clothes, linens and fabrics", questions: ["Perform techniques in sorting soiled clothes, linen and fabrics*", "Mend torn clothing, linen and fabric*", "Use appropriate chemical agents to remove stains*", "Observe safety precautions in the use of chemical agents*", "Perform laundry techniques and procedures*", "Operate clothes dryer according to manufacturer’s instructions*", "Provide maintenance for washing machine and clothes dryer*", "Perform the proper procedure and techniques in ironing*"] },
      { project: "Project 3", heading: "Establish professionalism at the workplace", questions: ["Exhibit willingness and enthusiasm and commitment to do the job*", "Observe positive work values and ethics*", "Maintain integrity and high degree of proficiency in the work place*", "Observe and maintains personal hygiene and good grooming at all times*"] },
    ],
  },
  "Driving NCII": {
    title: "Self-Assessment Guide - Driving NC II",
    sections: [
      { project: "Project : DRIVE LIGHT VEHICLE", heading: "Unit/s of Competency", title: "Unit/s of Competency", questions: ["Perform vehicle maintenance and minor servicing", "Perform light vehicle pre-starting and warm up", "Drive light vehicle", "Obey and observe traffic rules and regulation", "Practice road courtesy", "Implement and coordinate accident emergency procedures"] },
    ],
  },
  "Bartending NCII": {
    title: "Self-Assessment Guide - Bartending NC II",
    sections: [
      { heading: "CLEAN BAR AREAS", title: "CLEAN BAR AREAS", questions: ["Clean bar surface, tools and equipment", "Check working condition of equipments", "Check conditions of utensils and glassware for dirt and damages", "Clean and maintains identified public areas", "Remove empty and unwanted glasses on a regular basis with minimum disruption to customers", "Clean tables and service counter hygienically", "Perform bar cleaning procedures and workplace operations, safety and hygienic practices", "Use appropriate cleaning equipment and chemicals", "Dispose garbage properly"] },
      { heading: "OPERATE BAR", title: "OPERATE BAR", questions: ["Set up the bar display and work area", "Check and re-stock bar products and materials", "Identify and segregate bar products and materials", "Store all obtained items in accordance with established storing procedures and techniques", "Set up and segregate different glasses and bar tools", "Prepare suitable kinds of garnish presentation for cocktails, alcoholic and non-alcoholic drinks , coasters, edible and guest supplies", "Prepare appropriate ice supplies", "Check necessary bar tools, equipment and utensils", "Present drink list and recommends selection of drinks politely", "Check product and brand preference with the customer courteously", "Identify specific customer service preferences", "Recap customer’s order promptly", "Take and write down drink orders in order slip", "Perform proper pouring(into glass) and serving of beer", "Prepare ordered drinks and serve", "Perform proper technique and showmanship style in mixing", "Use appropriate glassware and service accessories", "Perform proper beverage service procedure", "Minimize waste and spillage in preparing", "Perform inventory procedure", "Use appropriate control system forms when necessary", "Perform replenishment of consumed items", "Store left over garnishes properly", "Keep materials, tools and glasses properly", "Remove beverage display and set up of bar area", "Keep all beverages in appropriate cabinets", "Keep properly materials, tools and glasses in suitable cabinets", "Perform proper sanitation practices"] },
      { heading: "PREPARE AND MIX COCKTAILS AND NON-ALCOHOLIC CONCOCTIONS", title: "PREPARE AND MIX COCKTAILS AND NON-ALCOHOLIC CONCOCTIONS", questions: ["Identify and select different types of bar tools and equipment", "Identify and select different types of glasses", "Prepare necessary ingredients and garnishes", "Prepare and mix range of cocktails, alcoholic and non-alcoholic drinks", "Apply appropriate mixing methods and procedures", "Use appropriate glass and service accessories to service to every mix drinks", "Use necessary garnishes appropriate to each cocktail and non-alcoholic drinks", "Use appropriate type of ice to every mixing procedure", "Use properly the necessary bar tools and mechanical equipment", "Clean glasses, bar tools and equipment after use", "Clean working area after mixing", "Observe sanitation, occupational health and safety practices"] },
      { heading: "PROVIDE BASIC WINE SERVICE", title: "PROVIDE BASIC WINE SERVICE", questions: ["Present wine list to customers", "Recommend appropriate wines for special occasions based on customer’s preference", "Answer customer queries about wines", "Take wine order slip and took out wine from cellar/storage", "Present wine to the customers and set up appropriate glassware and wine service accessories", "Demonstrate proper opening of wine", "Pour small amount of wine to host for tasting", "Demonstrate proper cork screw usage", "Examine the cork", "Demonstrate proper pouring of wines to customers", "Clear used and empty glasses", "Observe sanitation, occupational and safety practices"] },
    ],
  },
  "Agricultural Crops Production NCII": {
    title: "Self-Assessment Guide - Agricultural Crops Production NC II",
    sections: [
      { heading: "PERFORM NURSERY OPERATIONS", title: "PERFORM NURSERY OPERATIONS", questions: ["Prepare tools and simple equipment are according work requirements.", "Perform basic pre-operative activities such as checking of tools and equipment in accordance with manufacturer’s manual.", "Segregate and treat damaged and corroded tools according to maintenance plan and procedures.", "Maintain nursery sanitation according to GAP standard.", "Perform repair and maintenance of nursery facilities", "Apply preventive measures for inclement weather", "Practice safety measures according to OSHS", "Determine seeds/planting materials according to kinds and varieties.", "Select quality seeds according to prescribed characteristics", "Conduct seed testing to determine the percentage germination of the seed stock in accordance with the standard procedures", "Treat planting materials following standard protocol.", "Perform seed treatment for germination purposes based on type of crop*", "Prepare growing media according to prescribed mixture*", "Prepare seedbed based on crop species", "Place growing media in prescribed containers according to crop requirements", "Arrange and label pots or seedling trays according to varieties/species.", "Set-up a nursery shed according to plant requirement", "Select quality seedlings based on prescribed characteristics", "Perform plant propagation techniques based on recommended practices*", "Maintain the plant based on recommended practices", "Select quality seedlings and other propagation materials based on established criteria of the crop*"] },
      { heading: "PLANT CROPS", title: "PLANT CROPS", questions: ["Prepare tools and equipment for land clearing", "Clear the land according to prescribed methods of land preparation*", "Remove and dispose farm wastes according to waste management standards", "Collect soil samples for analysis based on standard procedure*", "Conduct land preparation according to crop requirement*", "Apply basal fertilizer based on crop requirement", "Prepare tools and materials for field lay-out", "Lay-out the prepared land in accordance with the recommended planting system*", "Perform digging of holes based on crop requirement*", "Separate dug out soil for covering the hole for planting", "Perform basal fertilizer application based on recommended amount", "Plant the seeds according to recommended rate, distance and depth*", "Replant according to recommended practices for a particular crop", "Perform proper handling of seedlings from nursery", "Transplant the seedlings based on crop practices*", "Transplant crops intended for container growing to appropriate containers and growing media.", "Replant the seedlings according to recommended practices for a particular crop", "Follow safety procedures according to Occupational Safety and Health Standards (OSHS) and Good Agricultural Practices (GAP)"] },
      { heading: "CARE AND MAINTAIN CROPS", title: "CARE AND MAINTAIN CROPS", questions: ["Monitor pest incidence based on prescribed procedure*", "Prepare tools and materials according to specific pest control measure.", "Follow appropriate pest control measures based on GAP*", "Observe and Practice Safety measures according to Occupational Safety and Health Standards (OSHS) Procedures", "Control weed population*", "Prepare Tools and materials according to prescribed user’s manual", "Identify kinds of Fertilizers", "Apply rate of Fertilizer based on crop requirement.", "Employs appropriate method of fertilizer application based on crop requirements.*", "Applies precautionary measures to avoid cross contamination based on GAP.", "Follows Safety procedures according to Occupational Safety and Health Standards.", "Determines soil moisture content based on soil field capacity", "Performs watering of crops following prescribed methods and schedule", "Observes Good Agricultural Practices", "Applies proper irrigation or watering of crops*", "Selects appropriate tools and materials for pruning.", "Performs pruning methods according to crops.*", "Follows Safety procedures are followed according to Occupational Safety and Health Standards", "Prepares tools and equipment for cultivation", "Carries out cultivation practices based on crop requirement*", "Performs rejuvenating activities*", "Performs growth training technique for different crops*", "Carries out mulching techniques*", "Follows safety procedures according to occupational safety and health standards"] },
      { heading: "CARRY-OUT HARVEST AND POSTHARVEST OPERATIONS", title: "CARRY-OUT HARVEST AND POSTHARVEST OPERATIONS", questions: ["Identify crop maturity indicator*", "Prepare materials, tools and equipment for harvesting and postharvest operations*", "Compare pest and diseases in storage to reference manual*", "Segregate harvested crop*", "Collect data on the environment (e.g. weather conditions, topography) and other relevant information (e.g. crop variety, cropping pattern/system, stage of crop)*", "Maintain records and provides feedback*", "Discuss labeling requirement for harvested produce*", "Follow guidelines and procedures for assessment activities, including occupational health and safety (OHS) requirements*", "Communicate effectively with farmers, team members and supervisor*", "Discuss personal hygiene, food safety, workplace sanitation", "Identify range of agricultural crop species/varieties", "Define farm planning and its principles", "Discuss industry standards for crops and regulating agencies", "Discuss postharvest treatments"] },
    ],
  },
} as const;
